#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KemishMusic
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KemishMusic")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::KemishMusic.Properties.Settings.Default.KemishMusicConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LeerPlaylist")]
		public ISingleResult<LeerPlaylistResult> LeerPlaylist()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LeerPlaylistResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCancion")]
		public ISingleResult<MostrarCancionResult> MostrarCancion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarCancionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LlenarCancionDatos")]
		public ISingleResult<LlenarCancionDatosResult> LlenarCancionDatos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string playlist_cancion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playlist_cancion);
			return ((ISingleResult<LlenarCancionDatosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCancionPlaylist3")]
		public int InsertarCancionPlaylist3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> playlist_playlist_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cancion_cancion_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string playlist_playlist_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string cancion_cancion_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playlist_playlist_id, cancion_cancion_id, playlist_playlist_nombre, cancion_cancion_nombre);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VerCancionPlaylist2")]
		public ISingleResult<VerCancionPlaylist2Result> VerCancionPlaylist2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string playlist_playlist_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playlist_playlist_nombre);
			return ((ISingleResult<VerCancionPlaylist2Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarPlaylist")]
		public int InsertarPlaylist([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string playlist_nombre)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playlist_nombre);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class LeerPlaylistResult
	{
		
		private string _playlist_nombre;
		
		public LeerPlaylistResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playlist_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string playlist_nombre
		{
			get
			{
				return this._playlist_nombre;
			}
			set
			{
				if ((this._playlist_nombre != value))
				{
					this._playlist_nombre = value;
				}
			}
		}
	}
	
	public partial class MostrarCancionResult
	{
		
		private string _cancion_nombre;
		
		public MostrarCancionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancion_nombre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string cancion_nombre
		{
			get
			{
				return this._cancion_nombre;
			}
			set
			{
				if ((this._cancion_nombre != value))
				{
					this._cancion_nombre = value;
				}
			}
		}
	}
	
	public partial class LlenarCancionDatosResult
	{
		
		private string _playlist_cancion_audionombre;
		
		private System.Data.Linq.Binary _playlist_cancion_imagen;
		
		public LlenarCancionDatosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playlist_cancion_audionombre", DbType="VarChar(200)")]
		public string playlist_cancion_audionombre
		{
			get
			{
				return this._playlist_cancion_audionombre;
			}
			set
			{
				if ((this._playlist_cancion_audionombre != value))
				{
					this._playlist_cancion_audionombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playlist_cancion_imagen", DbType="Image")]
		public System.Data.Linq.Binary playlist_cancion_imagen
		{
			get
			{
				return this._playlist_cancion_imagen;
			}
			set
			{
				if ((this._playlist_cancion_imagen != value))
				{
					this._playlist_cancion_imagen = value;
				}
			}
		}
	}
	
	public partial class VerCancionPlaylist2Result
	{
		
		private string _cancion_cancion_nombre;
		
		public VerCancionPlaylist2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cancion_cancion_nombre", DbType="VarChar(100)")]
		public string cancion_cancion_nombre
		{
			get
			{
				return this._cancion_cancion_nombre;
			}
			set
			{
				if ((this._cancion_cancion_nombre != value))
				{
					this._cancion_cancion_nombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
